site_name: Cloudmesh AI Storage
docs_dir: docs
use_directory_urls: false
theme:
  name: material
extra_css:
- css/custom.css
nav:
- Home: README.md
- Project:
  - Changelog: CHANGELOG.md
  - GitHub: https://github.com/cloudmesh-ai/cloudmesh-ai-storage
  - Issues: https://github.com/cloudmesh-ai/cloudmesh-ai-storage/issues
- API Reference: api.md
plugins:
- cloudmesh-ai-theme
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - src
        options:
          docstring_style: google
          show_submodules: true
          members: true
          docstring_section_style: table
          show_source: true
          group_by_category: true
          show_category_heading: true
          separate_signature: true
          show_root_full_path: true
